### ISSUE TITLE
App freezes when range exceeded

### ISSUE THREAD

**Issue by fanurs** [MSU-AI/safety-camera#14]
I saw that #13 has been merged into the main branch. So I took a look at it but found out something doesn't seem to work as what I would expect.

Basically when the audio range is exceeded, as shown in the terminal, I do see "Range exceeded" being printed out. But after that, the entire app just freezes, and the top right corner of the Streamlit run keeps showing "Connecting".

Did you guys encounter the same issue while pushing this feature?

Can we not have the app frozen once an alert is triggered? It's okay to print alert to terminal only.

![image](https://user-images.githubusercontent.com/21100851/231320825-6c4a7308-58da-4cd5-bcc6-6163b4016ef9.png)
![image](https://user-images.githubusercontent.com/21100851/231320861-7c6bcd42-3669-4c7a-a84f-266851edbccb.png)

**Comment by skap3214** [comment]
I added quit() right after it prints out the error message to essentially 'stop' the program. I have removed it now.

**Comment by fanurs** [comment]
@skap3214 I have reopened this issue because I don't see any commits associated to the fix you were referring to.
Anyway, I have removed two appearances of `quit()` that I see in `app/main.py`, and made a PR #15. Please check if this it is correct.
